### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by kelisisuoer** [zhitkur/Irregular#1]
I show an error in drvier.h when compiling the software

**Comment by zhitkur** [comment]
what exactly is the error?

**Comment by kelisisuoer** [comment]
![image](https://user-images.githubusercontent.com/88111168/127436754-8470d91b-2851-4b03-83ad-92121e9bbc08.png)
Maybe my operation is wrong

**Comment by zhitkur** [comment]
한국분이신거 같은데 디스코드로 알려드릴테니 친추 주세요.

**Comment by kelisisuoer** [comment]
그래서, 당신의 discord 계정 번호는 무엇입니까?
